[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
fs_permissions = [{ access = "read-write", path = "./"}]

# Simplified and corrected remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/contracts/src/v0.8/",
    "diamond-3-hardhat/=lib/diamond-3-hardhat/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
arbitrumSepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
arbitrumSepolia = { key = "${ARBISCAN_API_KEY}" }

[install]
no_auto_install = true  # Prevents automatic reinstallation of wrong packages